name: C++ CI - TeleTrackSim DAG

on:
  push:
    branches: [ master, "D*" ]
    paths:
      - "teletrack_sim/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ master, "D*" ]
    paths:
      - "teletrack_sim/**"

jobs:
  gnss:
    name: GNSS Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Configure GNSS
        run: cmake -S modules/gnss -B build/gnss
      - name: Build GNSS
        run: cmake --build build/gnss

  engine:
    name: Engine Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Configure Engine
        run: cmake -S modules/engine -B build/engine
      - name: Build Engine
        run: cmake --build build/engine

  logger:
    name: Logger Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Configure Logger
        run: cmake -S modules/logger -B build/logger
      - name: Build Logger
        run: cmake --build build/logger

  aggregator:
    name: Aggregator Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Configure Aggregator
        run: cmake -S modules/aggregator -B build/aggregator
      - name: Build Aggregator
        run: cmake --build build/aggregator

  step-checkout:
    name: Checkout + Setup (Full App)
    runs-on: ubuntu-latest
    needs: [gnss, engine, logger, aggregator]
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Conan
        run: pip install conan
      - name: Detect Conan Profile
        run: conan profile detect --force

  step-conan:
    name: Conan Install Deps
    runs-on: ubuntu-latest
    needs: step-checkout
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Conan Install
        run: conan install . -of=build --build=missing --conf tools.cmake.cmaketoolchain:generator=False

  step-cmake-configure:
    name: CMake Configure (Full App)
    runs-on: ubuntu-latest
    needs: step-conan
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: CMake Configure
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

  step-cmake-build:
    name: Build Full App
    runs-on: ubuntu-latest
    needs: step-cmake-configure
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: CMake Build
        run: cmake --build build

  step-run-app:
    name: Run Application
    runs-on: ubuntu-latest
    needs: step-cmake-build
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4
      - name: Run App
        run: ./build/teletrack_sim
