name: C++ CI - TeleTrack Sim (CMake DAG)

on:
  push:
    branches:
      - master
      - "D*"
    paths:
      - "teletrack_sim/**"
      - ".github/workflows/**" # <- include this so workflow updates also trigger!
  pull_request:
    branches:
      - master
      - "D*"
    paths:
      - "teletrack_sim/**"

jobs:
  gnss:
    name: Configure + Build GNSS Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4

      - name: Configure GNSS
        run: cmake -S modules/gnss -B build/gnss

      - name: Build GNSS
        run: cmake --build build/gnss

  engine:
    name: Configure + Build Engine Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4

      - name: Configure Engine
        run: cmake -S modules/engine -B build/engine

      - name: Build Engine
        run: cmake --build build/engine

  logger:
    name: Configure + Build Logger Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4

      - name: Configure Logger
        run: cmake -S modules/logger -B build/logger

      - name: Build Logger
        run: cmake --build build/logger

  aggregator:
    name: Configure + Build Aggregator Module (CMake)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4

      - name: Configure Aggregator
        run: cmake -S modules/aggregator -B build/aggregator

      - name: Build Aggregator
        run: cmake --build build/aggregator

  build-main:
    name: Build + Run Full App (CMake)
    needs: [gnss, engine, logger, aggregator]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: teletrack_sim
    steps:
      - uses: actions/checkout@v4

      - name: Cache full build
        uses: actions/cache@v3
        with:
          path: teletrack_sim/build
          key: main-${{ runner.os }}-${{ hashFiles('teletrack_sim/CMakeLists.txt') }}

      - name: Configure Full Build
        run: cmake -S . -B build

      - name: Build Full App
        run: cmake --build build

      - name: Run App
        run: ./build/teletrack_sim
